import {it,expect} from 'vitest'
import {freshDoc,replay,validateDoc,validateSeed,type ScoutDoc,type Event} from '../scouting/model'
let serial=0
const evt=(e:Record<string,unknown>)=>({...e,id:String(++serial),at:'2026-10-04T12:00:00Z'}) as Event
const point=(player=0,outcome='winner',smash=false)=>evt({kind:'point',player,outcome,smash})
it('scores errors for opponents and attributes errors to the selected player',()=>{const m=replay({...freshDoc(),events:[point(0),point(2,'forced'),point(1,'unforced')]});expect(m.score.currentGame).toEqual({a:30,b:15});expect(m.stats[2].forced).toBe(1);expect(m.stats[1].unforced).toBe(1)})
it('counts returned smashes without adding points',()=>{const m=replay({...freshDoc(),events:[evt({kind:'smash',player:0}),evt({kind:'smash',player:0}),point(0,'winner',true),point(0,'unforced',true)]});expect(m.stats[0]).toMatchObject({smashes:4,smashWinners:1,smashErrors:1});expect(m.points).toBe(2)})
it('undo restores score, stats and court ends',()=>{const d={...freshDoc(),events:Array.from({length:4},()=>point())};expect(replay(d).near).toBe('b');d.events.push(evt({kind:'undo'}));const m=replay(d);expect(m.near).toBe('a');expect(m.score.currentGame.a).toBe(40);expect(m.stats[0].winners).toBe(3)})
it('changes ends only after odd games',()=>{const d=freshDoc();for(let g=1;g<=4;g++){d.events.push(...Array.from({length:4},()=>point(g%2?0:2)));expect(replay(d).near).toBe(g<3?'b':'a')}})
it('activates Star Point after two lost advantages',()=>{const d=freshDoc();d.events.push(...[0,0,0,2,2,2,0,2,2,0].map(p=>point(p)));expect(replay(d).score.advantageReturns).toBe(2);d.events.push(point());expect(replay(d).score.sets[0]).toEqual({a:1,b:0})})
it('changes ends every six tie-break points',()=>{const d={...freshDoc(),events:[evt({kind:'score',seed:{sets:[{a:6,b:6}],game:{a:0,b:0},phase:'tiebreak',returns:0,server:0}}),...[0,2,0,2,0,2].map(p=>point(p))]};expect(replay(d).near).toBe('b')})
it('does not double-flip when a tie-break ends on point twelve',()=>{const d={...freshDoc(),events:[evt({kind:'score',seed:{sets:[{a:6,b:6}],game:{a:6,b:5},phase:'tiebreak',returns:0,server:0}}),point()]};expect(replay(d).near).toBe('b');expect(replay(d).score.sets).toEqual([{a:7,b:6},{a:0,b:0}])})
it('keeps imported scores out of observed player statistics',()=>{const d={...freshDoc(),events:[point(),evt({kind:'score',seed:{sets:[{a:6,b:4},{a:3,b:2}],game:{a:30,b:15},phase:'playing',returns:0,server:2}})]};expect(replay(d).points).toBe(1);expect(replay(d).stats[0].winners).toBe(1)})
it('rejects impossible seeds and duplicated events',()=>{expect(()=>validateSeed({sets:[{a:6,b:4}],game:{a:0,b:0},phase:'playing',returns:0,server:0})).toThrow();expect(()=>validateDoc({...freshDoc(),events:[point(4)]})).toThrow();const p=point();expect(()=>validateDoc({...freshDoc(),events:[p,p]})).toThrow()})
it('rotates all selected servers',()=>{const d:ScoutDoc={...freshDoc(),firstServer:1,otherServer:3};expect(replay(d).server).toBe(1);for(const server of [3,0,2,1]){d.events.push(...Array.from({length:4},()=>point()));expect(replay(d).server).toBe(server)}})
