// @vitest-environment jsdom
import {createElement} from 'react'
import {afterEach,beforeEach,it,expect,vi} from 'vitest'
import {render,screen,fireEvent,waitFor,cleanup,within} from '@testing-library/react'
import Scout from '../../app/(app)/scouting/[id]/Scout'
import {freshDoc,replay} from '../scouting/model'
vi.mock('next/link',()=>({default:(props:Record<string,unknown>)=>createElement('a',props)}))
const players=['One','Two','Three','Four'].map((name,i)=>({id:String(i),name}))
beforeEach(()=>{vi.restoreAllMocks();HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};const storage=new Map<string,string>();vi.stubGlobal('localStorage',{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,v),removeItem:(k:string)=>storage.delete(k),clear:()=>storage.clear()})})
afterEach(()=>{cleanup();vi.unstubAllGlobals()})
it('recovers roster and observation history after an offline reload',async()=>{
 localStorage.setItem('pn-scout-v1:offline',JSON.stringify({players,revision:3,document:freshDoc()}))
 vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('offline')))
 render(createElement(Scout,{matchId:'offline'}))
 await screen.findByText(/Working from your local recovery copy/)
 fireEvent.keyDown(window,{code:'Space',key:' '})
 await screen.findByText('One · Rally in progress')
 expect(JSON.parse(localStorage.getItem('pn-scout-v1:offline')!).document.events[0].kind).toBe('rally_start')
 expect(JSON.parse(localStorage.getItem('pn-scout-v1:offline')!).players).toEqual(players)
})
it('Space never records a fault on a focused button or starts an extra rally',async()=>{
 let revision=1
 const fetch=vi.fn(async(_url:unknown,opts?:RequestInit)=>Response.json(opts?.method==='POST'?{revision:++revision}:{players,session:{revision,document:freshDoc()}}))
 vi.stubGlobal('fetch',fetch);render(createElement(Scout,{matchId:'keys'}))
 await screen.findByRole('button',{name:'Start rally Space'})
 fireEvent.keyDown(window,{code:'Space',key:' '})
 expect(screen.queryByRole('button',{name:'Start rally Space'})).toBeNull()
 const fault=await screen.findByRole('button',{name:'First-serve fault'})
 fireEvent.keyDown(fault,{code:'Space',key:' '});fireEvent.keyUp(fault,{code:'Space',key:' '})
 await waitFor(()=>expect(JSON.parse(localStorage.getItem('pn-scout-v1:keys')!).document.events).toHaveLength(1))
 expect((screen.getByRole('button',{name:'Double fault'}) as HTMLButtonElement).disabled).toBe(true)
})
it('blocks further input when another window has changed the session',async()=>{
 vi.stubGlobal('fetch',vi.fn(async(_url:unknown,opts?:RequestInit)=>opts?.method==='POST'?Response.json({error:'Session changed'},{status:409}):Response.json({players,session:{revision:1,document:freshDoc()}})))
 render(createElement(Scout,{matchId:'conflict'}));await screen.findByRole('button',{name:'Start rally Space'});fireEvent.keyDown(window,{code:'Space',key:' '})
 await screen.findByText('Session changed');expect((screen.getByRole('button',{name:'First-serve fault'}) as HTMLButtonElement).disabled).toBe(true)
 expect(screen.getByRole('button',{name:'Download local copy'})).toBeTruthy()
})
it('records pair arrivals before showing servers and prevents Space from starting early',async()=>{
 let revision=0
 vi.stubGlobal('fetch',vi.fn(async(_url:unknown,opts?:RequestInit)=>Response.json(opts?.method==='POST'?{revision:++revision}:{players,session:null})))
 render(createElement(Scout,{matchId:'arrivals'}))
 await screen.findByRole('heading',{name:'1. Pairs on court'})
 expect(screen.queryByLabelText('First server')).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:'Mark pair A on court'}))
 await waitFor(()=>expect(JSON.parse(localStorage.getItem('pn-scout-v1:arrivals')!).document.events).toHaveLength(1))
 fireEvent.keyDown(window,{code:'Space',key:' '})
 expect(JSON.parse(localStorage.getItem('pn-scout-v1:arrivals')!).document.events).toHaveLength(1)
 expect((screen.getByRole('button',{name:'Next: servers & positions'}) as HTMLButtonElement).disabled).toBe(true)
 fireEvent.click(screen.getByRole('button',{name:'Mark pair B on court'}))
 fireEvent.click(screen.getByRole('button',{name:'Next: servers & positions'}))
 expect(screen.getByRole('heading',{name:'2. Servers & positions'})).toBeTruthy()
 fireEvent.change(screen.getByLabelText('First server'),{target:{value:'3'}})
 fireEvent.click(screen.getByRole('button',{name:'Confirm court & start scouting'}))
 await screen.findByRole('button',{name:'Start rally Space'})
 const document=JSON.parse(localStorage.getItem('pn-scout-v1:arrivals')!).document
 expect(document.events.map((e:{kind:string})=>e.kind)).toEqual(['pair_arrived','pair_arrived','court_setup'])
 expect(document.events[2].settings.firstServer).toBe(3)
 await waitFor(()=>expect(screen.getByText('Saved')).toBeTruthy())
})
it('restores saved arrivals after a reload without exposing the live court',async()=>{
 const document={...freshDoc(),preparation:true,events:[{id:'arrival',at:'2026-10-04T12:00:00Z',kind:'pair_arrived',team:'a'}]}
 vi.stubGlobal('fetch',vi.fn(async()=>Response.json({players,session:{revision:1,document}})))
 render(createElement(Scout,{matchId:'restore-arrival'}))
 await screen.findByText('On court')
 expect(screen.queryByRole('button',{name:'Mark pair A on court'})).toBeNull()
 expect(screen.getByRole('button',{name:'Mark pair B on court'})).toBeTruthy()
 expect(screen.queryByRole('button',{name:'Start rally Space'})).toBeNull()
})

it('changes server directly on the court during a second serve and supports undo',async()=>{
 let revision=1
 vi.stubGlobal('fetch',vi.fn(async(_url:unknown,opts?:RequestInit)=>Response.json(opts?.method==='POST'?{revision:++revision}:{players,session:{revision,document:freshDoc()}})))
 render(createElement(Scout,{matchId:'change-server'}))
 await screen.findByRole('button',{name:'Start rally Space'})
 fireEvent.keyDown(window,{code:'Space',key:' '})
 fireEvent.click(screen.getByRole('button',{name:'First-serve fault'}))
 fireEvent.click(screen.getByRole('button',{name:'Scouting menu'}))
 expect((screen.getByLabelText('Server') as HTMLSelectElement).disabled).toBe(false)
 fireEvent.click(screen.getByRole('button',{name:'Scouting menu'}))
 fireEvent.click(screen.getByRole('button',{name:'Set Three as server'}))
 expect(screen.getByText('Three · Second serve')).toBeTruthy()
 expect(screen.queryByRole('button',{name:'Start rally Space'})).toBeNull()
 expect(screen.getByText('Server changed to Three · current rally kept')).toBeTruthy()
 expect((screen.getByRole('button',{name:'Double fault'}) as HTMLButtonElement).disabled).toBe(false)
 fireEvent.click(screen.getByRole('button',{name:'Undo last action'}))
 expect(screen.getByText('One · Second serve')).toBeTruthy()
 await waitFor(()=>expect(screen.getByText('Saved')).toBeTruthy())
})
const reordered=(value:unknown):any=>Array.isArray(value)?value.map(reordered):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).sort(([a],[b])=>b.localeCompare(a)).map(([k,v])=>[k,reordered(v)])):value
const rallyStart={kind:'rally_start' as const,id:'rally',at:'2026-10-04T12:00:00Z'}
it('resumes an identical saved rally after reload despite reordered database keys',async()=>{
 const document={...freshDoc(),events:[rallyStart]}
 localStorage.setItem('pn-scout-v1:ordered',JSON.stringify({revision:2,players,document}))
 const fetch=vi.fn(async()=>Response.json({players,session:{revision:2,document:reordered(document)}}))
 vi.stubGlobal('fetch',fetch);render(createElement(Scout,{matchId:'ordered'}))
 await screen.findByText('One · Rally in progress')
 expect(screen.queryByText(/Local and server sessions differ/)).toBeNull()
 expect(fetch).toHaveBeenCalledTimes(1)
})
it('recovers and syncs unsaved local points after a reload with reordered server history',async()=>{
 const remote={...freshDoc(),events:[rallyStart]}
 const local={...remote,events:[...remote.events,{kind:'point' as const,player:0 as const,outcome:'winner' as const,smash:false,id:'winner',at:'2026-10-04T12:00:12Z'}]}
 localStorage.setItem('pn-scout-v1:pending',JSON.stringify({revision:1,players,document:local}))
 const fetch=vi.fn(async(_url:unknown,opts?:RequestInit)=>Response.json(opts?.method==='POST'?{revision:3}:{players,session:{revision:2,document:reordered(remote)}}))
 vi.stubGlobal('fetch',fetch);render(createElement(Scout,{matchId:'pending'}))
 await screen.findByRole('button',{name:'Start rally Space'})
 await waitFor(()=>expect(fetch).toHaveBeenCalledTimes(2))
 const payload=JSON.parse(fetch.mock.calls[1][1]!.body as string)
 expect(payload).toEqual({revision:2,document:local})
 await waitFor(()=>expect(screen.getByText('Saved')).toBeTruthy())
 expect(screen.queryByText(/Local and server sessions differ/)).toBeNull()
 expect(JSON.parse(localStorage.getItem('pn-scout-v1:pending')!).document.events).toHaveLength(2)
})
it('chooses a longer server history without overwriting it after reload',async()=>{
 const local=freshDoc(),remote={...local,events:[rallyStart]}
 localStorage.setItem('pn-scout-v1:remote-ahead',JSON.stringify({revision:1,players,document:local}))
 const fetch=vi.fn(async()=>Response.json({players,session:{revision:2,document:reordered(remote)}}))
 vi.stubGlobal('fetch',fetch);render(createElement(Scout,{matchId:'remote-ahead'}))
 await screen.findByText('One · Rally in progress')
 expect(fetch).toHaveBeenCalledTimes(1)
 expect(JSON.parse(localStorage.getItem('pn-scout-v1:remote-ahead')!).document.events).toEqual([rallyStart])
 expect(screen.queryByText(/Local and server sessions differ/)).toBeNull()
})
it('still blocks genuinely divergent local and server histories',async()=>{
 localStorage.setItem('pn-scout-v1:diverged',JSON.stringify({revision:1,players,document:{...freshDoc(),events:[rallyStart]}}))
 const fetch=vi.fn(async()=>Response.json({players,session:{revision:2,document:reordered({...freshDoc(),events:[{...rallyStart,id:'other-rally'}]})}}))
 vi.stubGlobal('fetch',fetch);render(createElement(Scout,{matchId:'diverged'}))
 await screen.findByText(/Local and server sessions differ/)
 expect(fetch).toHaveBeenCalledTimes(1)
 expect(screen.getByRole('button',{name:'Download local copy'})).toBeTruthy()
})
it('hides the header and keeps secondary actions in the scouting menu',async()=>{
 vi.stubGlobal('fetch',vi.fn(async()=>Response.json({players,session:{revision:1,document:freshDoc()}})))
 const {container}=render(createElement(Scout,{matchId:'focus-mode'}))
 await screen.findByRole('button',{name:'Start rally Space'})
 expect(container.querySelector('[data-scout-focus="true"]')).toBeTruthy()
 expect(screen.queryByRole('button',{name:'Export session (JSON)'})).toBeNull()
 expect(container.querySelector('header')).toBeNull()
 fireEvent.click(screen.getByLabelText('Scouting menu'))
 fireEvent.click(screen.getByRole('button',{name:'Show admin'}))
 expect(container.querySelector('[data-scout-focus="true"]')).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:'Focus court'}))
 fireEvent.click(screen.getByRole('button',{name:'Insights'}))
 expect(screen.getByRole('button',{name:'Export session (JSON)'})).toBeTruthy()
 expect(container.querySelector('[data-scout-focus="true"]')).toBeTruthy()
})
it('does not start a hidden rally with Space in portrait landscape-only mode',async()=>{
 vi.stubGlobal('matchMedia',vi.fn(()=>({matches:true})))
 vi.stubGlobal('fetch',vi.fn(async()=>Response.json({players,session:{revision:1,document:freshDoc()}})))
 render(createElement(Scout,{matchId:'landscape-only',landscapeOnly:true}))
 await screen.findByRole('button',{name:'Start rally Space'})
 fireEvent.keyDown(window,{code:'Space',key:' '})
 expect(JSON.parse(localStorage.getItem('pn-scout-v1:landscape-only')!).document.events).toHaveLength(0)
 expect(screen.getByText('Rotate your phone')).toBeTruthy()
})
it('classifies winners and counts a previously logged winning smash only once',async()=>{
 let revision=1
 vi.stubGlobal('fetch',vi.fn(async(_url:unknown,opts?:RequestInit)=>Response.json(opts?.method==='POST'?{revision:++revision}:{players,session:{revision,document:freshDoc()}})))
 render(createElement(Scout,{matchId:'winner-picker'}))
 await screen.findByRole('button',{name:'Start rally Space'})
 fireEvent.click(screen.getByRole('button',{name:'Start rally Space'}))
 fireEvent.click(screen.getByRole('button',{name:'Smash attempt for One'}))
 const card=screen.getByRole('article',{name:'One'})
 fireEvent.click(within(card).getByRole('button',{name:'Winner'}))
 expect(replay(JSON.parse(localStorage.getItem('pn-scout-v1:winner-picker')!).document).points).toBe(0)
 fireEvent.click(screen.getByRole('button',{name:'Smash'}))
 fireEvent.click(screen.getByRole('checkbox',{name:/Smash already counted/}))
 fireEvent.click(screen.getByRole('button',{name:'Smash'}))
 fireEvent.click(screen.getByRole('button',{name:'Save winner'}))
 let model=replay(JSON.parse(localStorage.getItem('pn-scout-v1:winner-picker')!).document)
 expect(model.stats[0]).toMatchObject({smashes:1,smashWinners:1,winners:1})
 expect(model.points).toBe(1)
 fireEvent.click(screen.getByRole('button',{name:'Undo last action'}))
 model=replay(JSON.parse(localStorage.getItem('pn-scout-v1:winner-picker')!).document)
 expect(model.stats[0]).toMatchObject({smashes:1,smashWinners:0,winners:0})
 fireEvent.click(within(card).getByRole('button',{name:'Winner'}))
 fireEvent.click(screen.getByRole('button',{name:'Smash'}))
 fireEvent.click(screen.getByRole('button',{name:'Save winner'}))
 model=replay(JSON.parse(localStorage.getItem('pn-scout-v1:winner-picker')!).document)
 expect(model.stats[0]).toMatchObject({smashes:2,smashWinners:1,winners:1})
 fireEvent.click(screen.getByRole('button',{name:'Start rally Space'}))
 fireEvent.click(within(card).getByRole('button',{name:'Winner'}))
 fireEvent.click(screen.getByRole('button',{name:'Cancel'}))
 expect(screen.queryByRole('button',{name:'Save winner'})).toBeNull()
 fireEvent.click(within(card).getByRole('button',{name:'Winner'}))
 fireEvent.click(screen.getByRole('button',{name:'Save winner'}))
 model=replay(JSON.parse(localStorage.getItem('pn-scout-v1:winner-picker')!).document)
 expect(model.stats[0]).toMatchObject({smashes:2,smashWinners:1,winners:2})
})
it('saves optional winner tags and classifies errors without winner-only tags',async()=>{
 let revision=1
 vi.stubGlobal('fetch',vi.fn(async(_url:unknown,opts?:RequestInit)=>Response.json(opts?.method==='POST'?{revision:++revision}:{players,session:{revision,document:freshDoc()}})))
 render(createElement(Scout,{matchId:'shot-tags'}))
 await screen.findByRole('button',{name:'Start rally Space'})
 fireEvent.click(screen.getByRole('button',{name:'Start rally Space'}))
 fireEvent.click(within(screen.getByRole('article',{name:'One'})).getByRole('button',{name:'Winner'}))
 fireEvent.click(screen.getByRole('button',{name:'Volley'}))
 fireEvent.click(screen.getByRole('button',{name:'Backhand'}))
 fireEvent.keyDown(screen.getByRole('button',{name:'Volley'}),{key:'a'})

 fireEvent.click(screen.getByRole('switch',{name:/Outside-court recovery/}))
 fireEvent.click(screen.getByRole('switch',{name:'Smash recovery'}))
 fireEvent.click(screen.getByRole('button',{name:'Lucky'}))
 fireEvent.keyDown(screen.getByRole('button',{name:'Save winner'}),{key:'Enter',ctrlKey:true})
 const doc=()=>JSON.parse(localStorage.getItem('pn-scout-v1:shot-tags')!).document
 expect(doc().events.at(-1)).toMatchObject({shot:'volley',side:'backhand',assistBy:1,recovery:true,smashRecovery:true,netCord:'lucky'})
 fireEvent.click(screen.getByRole('button',{name:'Start rally Space'}))
 fireEvent.click(within(screen.getByRole('article',{name:'Three'})).getByRole('button',{name:'Unforced error'}))
 expect(screen.queryByRole('checkbox',{name:/Teammate assist/})).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:'Gancho'}))
 fireEvent.click(screen.getByRole('button',{name:'Unlucky'}))
 fireEvent.click(screen.getByRole('button',{name:'Save unforced error'}))
 expect(doc().events.at(-1)).toMatchObject({outcome:'unforced',shot:'gancho',smash:false,netCord:'unlucky'})
 expect(doc().events.at(-1).assistBy).toBeUndefined()
})
