'use client'
import {useEffect,useState} from 'react'
import {useSearchParams} from 'next/navigation'
export default function TeamAccess(){
 const params=useSearchParams();const matchId=params.get('match'),kind=params.get('kind');
 const [assignee,setAssignee]=useState('');
 async function assign(){setBusy(true);try{const r=await fetch('/api/internal/scouting-assignment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({matchId,kind,email:assignee})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage('Session reassigned. The new scouter should load the server copy before recording.')}catch(e){setMessage(e instanceof Error?e.message:'Could not assign session.')}finally{setBusy(false)}}
 const [email,setEmail]=useState(''),[data,setData]=useState<{grants:any[];admins:any[]}>({grants:[],admins:[]}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 async function load(){try{const r=await fetch('/api/internal/team-access');const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch{setMessage('Could not load access. Check that the database update is installed.')}}
 useEffect(()=>{void load()},[])
 async function update(email:string,status:string){setBusy(true);try{const r=await fetch('/api/internal/team-access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,status})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage(status==='active'?'Scouter access granted. They can sign in with this email; no invitation email has been sent.':'Access suspended. Local unsynced work stays on their device.');setEmail('');await load()}catch(e){setMessage(e instanceof Error?e.message:'Could not update access.')}finally{setBusy(false)}}
 return <section style={{maxWidth:1000,padding:24}}><h1>Team access</h1><p>Scouters can record matches and view all scouting insights. Only administrators can manage access or change someone else’s assigned session.</p><form className="ui-panel" onSubmit={e=>{e.preventDefault();void update(email,'active')}} style={{padding:20,display:'flex',gap:12,alignItems:'end'}}><label>Email<input className="ui-input" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="scouter@example.com"/></label><span>Role: Scouter</span><button className="ui-btn" data-variant="primary" disabled={busy}>Grant access</button></form><p role="status">{message}</p>{matchId&&<form className="ui-panel" style={{padding:20,marginBottom:20}} onSubmit={e=>{e.preventDefault();void assign()}}><h2>Assign scouting session</h2><p>Existing recorded points stay intact. Pending saves from the previous scouter will be blocked.</p><label>Active scouter <select required className="ui-input" value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Choose a person</option>{data.grants.filter(g=>g.user_id&&g.status==='active').map(g=><option key={g.email} value={g.email}>{g.email}</option>)}</select></label> <button className="ui-btn" disabled={busy||!assignee}>Assign session</button></form>}<div className="ui-panel" style={{padding:20}}><h2>People</h2>{data.admins.map(a=><p key={a.id}>{a.email} · Administrator · protected</p>)}{data.grants.map(g=><div key={g.email} style={{display:'flex',gap:16,padding:'14px 0',alignItems:'center',borderTop:'1px solid var(--border)'}}><span style={{flex:1}}>{g.email}<br/><small>Scouter · {g.status==='suspended'?'Suspended':g.user_id?'Active':'Awaiting verified sign-in'}</small></span><button className="ui-btn" disabled={busy} onClick={()=>update(g.email,g.status==='active'?'suspended':'active')}>{g.status==='active'?'Suspend':'Restore access'}</button></div>)}</div></section>
}
