export const reminderCopy = {
  en: {
    subject: 'Your padel today 🎾',
    eyebrow: 'PADEL PREDICT',
    title: 'Today’s matches.\nYour picks.',
    intro: 'Make your predictions, then follow the action.',
    pick: 'Make your picks',
    all: 'See today’s matches',
    footer: 'You enabled Padel Predict reminders.',
    manage: 'Manage reminders',
    unsubscribe: 'Unsubscribe',
    pushSingle: '{pair1} vs {pair2} starts soon. Make your picks.',
    pushTitle: 'Before the first serve 🎾',
    pushBody:
      '{matches} matches · {questions} predictions open. Make your picks.',
    settingsTitle: 'Your padel reminders',
    email: 'Your padel today',
    emailSub: 'One email with today’s matches and available predictions.',
    push: 'Before the first serve',
    pushSub: 'A reminder before a match you follow. At most one a day.',
    saved: 'Saved',
    error: 'Could not save. Try again.',
    done: 'Email reminders turned off.',
    confirm: 'Turn off daily emails',
    men: 'Men',
    women: 'Women',
  },
  es: {
    subject: 'Tu pádel de hoy 🎾',
    eyebrow: 'PADEL PREDICT',
    title: 'Los partidos de hoy.\nTus pronósticos.',
    intro: 'Haz tus pronósticos y sigue la acción.',
    pick: 'Haz tus pronósticos',
    all: 'Ver los partidos de hoy',
    footer: 'Has activado los recordatorios de Padel Predict.',
    manage: 'Gestionar recordatorios',
    unsubscribe: 'Cancelar suscripción',
    pushSingle: '{pair1} vs {pair2} empieza pronto. Haz tus pronósticos.',
    pushTitle: 'Antes del primer saque 🎾',
    pushBody:
      '{matches} partidos · {questions} pronósticos disponibles. Elige los tuyos.',
    settingsTitle: 'Tus recordatorios de pádel',
    email: 'Tu pádel de hoy',
    emailSub:
      'Un correo con los partidos de hoy y los pronósticos disponibles.',
    push: 'Antes del primer saque',
    pushSub: 'Un aviso antes de un partido que sigues. Como máximo uno al día.',
    saved: 'Guardado',
    error: 'No se pudo guardar. Inténtalo de nuevo.',
    done: 'Recordatorios por correo desactivados.',
    confirm: 'Desactivar los correos diarios',
    men: 'Hombres',
    women: 'Mujeres',
  },
  pt: {
    subject: 'Seu padel de hoje 🎾',
    eyebrow: 'PADEL PREDICT',
    title: 'Os jogos de hoje.\nSeus palpites.',
    intro: 'Faça seus palpites e acompanhe os jogos.',
    pick: 'Faça seus palpites',
    all: 'Ver os jogos de hoje',
    footer: 'Você ativou os lembretes do Padel Predict.',
    manage: 'Gerenciar lembretes',
    unsubscribe: 'Cancelar inscrição',
    pushSingle: '{pair1} vs {pair2} começa em breve. Faça seus palpites.',
    pushTitle: 'Antes do primeiro saque 🎾',
    pushBody:
      '{matches} jogos · {questions} palpites disponíveis. Faça os seus.',
    settingsTitle: 'Seus lembretes de padel',
    email: 'Seu padel de hoje',
    emailSub: 'Um e-mail com os jogos de hoje e os palpites disponíveis.',
    push: 'Antes do primeiro saque',
    pushSub:
      'Um lembrete antes de um jogo que você acompanha. No máximo um por dia.',
    saved: 'Salvo',
    error: 'Não foi possível salvar. Tente novamente.',
    done: 'Lembretes por e-mail desativados.',
    confirm: 'Desativar e-mails diários',
    men: 'Masculino',
    women: 'Feminino',
  },
  fr: {
    subject: 'Votre padel du jour 🎾',
    eyebrow: 'PADEL PREDICT',
    title: 'Les matchs du jour.\nVos pronostics.',
    intro: 'Faites vos pronostics et suivez les matchs.',
    pick: 'Faire mes pronostics',
    all: 'Voir les matchs du jour',
    footer: 'Vous avez activé les rappels Padel Predict.',
    manage: 'Gérer les rappels',
    unsubscribe: 'Se désabonner',
    pushSingle: '{pair1} vs {pair2} commence bientôt. Faites vos pronostics.',
    pushTitle: 'Avant le premier service 🎾',
    pushBody:
      '{matches} matchs · {questions} pronostics disponibles. Faites vos choix.',
    settingsTitle: 'Vos rappels de padel',
    email: 'Votre padel du jour',
    emailSub:
      'Un e-mail avec les matchs du jour et les pronostics disponibles.',
    push: 'Avant le premier service',
    pushSub: 'Un rappel avant un match que vous suivez. Un par jour maximum.',
    saved: 'Enregistré',
    error: 'Impossible d’enregistrer. Réessayez.',
    done: 'Rappels par e-mail désactivés.',
    confirm: 'Désactiver les e-mails quotidiens',
    men: 'Hommes',
    women: 'Femmes',
  },
  it: {
    subject: 'Il tuo padel di oggi 🎾',
    eyebrow: 'PADEL PREDICT',
    title: 'Le partite di oggi.\nI tuoi pronostici.',
    intro: 'Fai i tuoi pronostici e segui le partite.',
    pick: 'Fai i tuoi pronostici',
    all: 'Vedi le partite di oggi',
    footer: 'Hai attivato i promemoria di Padel Predict.',
    manage: 'Gestisci i promemoria',
    unsubscribe: 'Annulla iscrizione',
    pushSingle: '{pair1} vs {pair2} inizia tra poco. Fai i tuoi pronostici.',
    pushTitle: 'Prima del primo servizio 🎾',
    pushBody:
      '{matches} partite · {questions} pronostici disponibili. Fai le tue scelte.',
    settingsTitle: 'I tuoi promemoria di padel',
    email: 'Il tuo padel di oggi',
    emailSub: 'Un’e-mail con le partite di oggi e i pronostici disponibili.',
    push: 'Prima del primo servizio',
    pushSub:
      'Un promemoria prima di una partita che segui. Al massimo uno al giorno.',
    saved: 'Salvato',
    error: 'Impossibile salvare. Riprova.',
    done: 'Promemoria via e-mail disattivati.',
    confirm: 'Disattiva le e-mail giornaliere',
    men: 'Uomini',
    women: 'Donne',
  },
} as const
export type ReminderLocale = keyof typeof reminderCopy
export function reminderLocale(raw: string | null | undefined): ReminderLocale {
  return raw && raw in reminderCopy ? (raw as ReminderLocale) : 'en'
}
export const appBase = 'https://padelnachos.com'
export function appPath(locale: ReminderLocale, path: string) {
  return `${locale === 'en' ? '' : `/${locale}`}${path}`
}
