// Fills the player FKs on Pro Padel League fixtures, from the line-ups their
// event schedule page publishes on the day.
//
// Without this a live event renders as "TBD vs TBD": the static payload gives
// us the fixture (which franchises, when) but never who takes the court.
//
// Defaults to a DRY RUN. Pass --apply to write.
// Idempotent: a match that already has four player FKs is skipped unless
// --force, so re-running as later days are published only fills new rows.
//
// Capture needs a browser, which this project's laptops lack, so the same
// seam as the standings scraper: --emit-capture writes a self-contained
// script for the Railway container, --capture reads its JSON back here.
//
// Usage:
//   npx tsx scripts/import-ppl-lineups.ts --emit-capture /tmp/cap.mjs
//   npx tsx scripts/import-ppl-lineups.ts --capture /tmp/out.json
//   npx tsx scripts/import-ppl-lineups.ts --capture /tmp/out.json --apply

import fs from 'node:fs'
import { createClient } from '@supabase/supabase-js'
import { extractLineupDom, type RawLineupCourtDom } from './lib/ppl-lineup-dom'
import { parseLineups, alignLineupToTie } from './lib/ppl-lineup-parse'
import { PPL_ORIGIN, PPL_USER_AGENT, fetchBuildId, type Fetcher } from './lib/ppl-source'

if (fs.existsSync('.env.local')) {
  for (const line of fs.readFileSync('.env.local', 'utf8').split('\n')) {
    const m = line.match(/^([A-Z_]+)=(.*)$/)
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2]
  }
}
for (const k of ['SUPABASE_URL', 'SUPABASE_SERVICE_KEY']) {
  if (!process.env[k]) throw new Error(`missing ${k}`)
}

const APPLY = process.argv.includes('--apply')
const FORCE = process.argv.includes('--force')
function arg(name: string): string | null {
  const i = process.argv.indexOf(`--${name}`)
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : null
}
const EMIT = arg('emit-capture')
const CAPTURE = arg('capture')
const SLUG = arg('slug') ?? 'playa-del-carmen'

const supabase = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_KEY!)

const nodeFetch: Fetcher = async (url) => {
  const r = await fetch(url, { headers: { 'user-agent': PPL_USER_AGENT } })
  return { status: r.status, text: () => r.text() }
}

/** Loose name key: accent- and case-insensitive, punctuation dropped. */
function nameKey(n: string): string {
  return n.normalize('NFD').replace(/[̀-ͯ]/g, '')
    .toLowerCase().replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim()
}

async function main() {
  console.log(APPLY ? '*** APPLY MODE — this will write ***' : '--- DRY RUN (pass --apply to write) ---')

  if (EMIT) {
    // Day tabs are BUTTONS that swap the grid client-side, not links — a
    // ?day= query parameter does nothing, so each day has to be clicked.
    //
    // And the wait has to be on `.matchgroup`, not `.cc-live-match__team`:
    // that class also appears in the "upcoming" strip at the top of the page,
    // so waiting on it succeeds while the detailed grid is still empty. That
    // is exactly how the first capture returned 0 courts for all four days
    // without erroring.
    const script = `// GENERATED by import-ppl-lineups.ts --emit-capture. Do not edit.
const URL = ${JSON.stringify(`${PPL_ORIGIN}/tournament/${SLUG}/`)}
const extractLineupDom = ${extractLineupDom.toString()}
;(async () => {
  const pw = await import('playwright')
  const b = await pw.chromium.launch({ args: ['--no-sandbox', '--disable-dev-shm-usage'] })
  const p = await b.newPage()
  // The serialised function carries the TypeScript compiler's __name helper,
  // which does not exist in the page.
  await p.addInitScript(() => { globalThis.__name = (f) => f })
  const out = {}
  try {
    // NOT networkidle — these pages hold an open Firestore long-poll.
    await p.goto(URL, { waitUntil: 'domcontentloaded', timeout: 30000 })
    await p.waitForSelector('.matchgroup', { timeout: 30000 })
    const tabs = await p.$$('.cc-bcast-day-tabs__tab')
    for (let i = 0; i < tabs.length; i++) {
      const label = (await tabs[i].innerText()).replace(/\\s+/g, ' ').trim()
      try {
        await tabs[i].click()
        await p.waitForTimeout(1200)
        await p.waitForSelector('.matchgroup', { timeout: 15000 })
        out[label] = await p.evaluate(extractLineupDom)
      } catch (e) {
        out[label] = { error: String(e && e.message ? e.message : e).split('\\n')[0] }
      }
    }
  } catch (e) {
    out['__page'] = { error: String(e && e.message ? e.message : e).split('\\n')[0] }
  }
  await b.close()
  console.log('BEGIN_JSON')
  console.log(JSON.stringify(out))
  process.exit(0)
})()
`
    fs.writeFileSync(EMIT, script)
    console.log(`wrote capture script: ${EMIT} (clicks every day tab)`)
    return
  }

  if (!CAPTURE) throw new Error('pass --capture <file> (produce it with --emit-capture)')
  const raw = JSON.parse(fs.readFileSync(CAPTURE, 'utf8')) as Record<string, RawLineupCourtDom[] | { error: string }>

  const courts: RawLineupCourtDom[] = []
  for (const [url, v] of Object.entries(raw)) {
    if (!Array.isArray(v)) { console.log(`  ${url}: capture error — ${v.error}`); continue }
    console.log(`  ${url}: ${v.length} court(s)`)
    courts.push(...v)
  }

  const { parsed, problems } = parseLineups(courts)
  console.log(`\nparsed ${parsed.length} court(s), ${problems.length} refused`)
  for (const p of problems) console.log(`  REFUSED ${p.label} ${p.gender}: ${p.reason} — ${p.detail}`)

  // Our side.
  const { data: tour } = await supabase.from('tournaments')
    .select('id').eq('source', 'ppl').eq('external_id', SLUG).single()
  if (!tour) throw new Error(`tournament ${SLUG} not found`)

  const { data: ties } = await supabase.from('league_ties')
    .select('id,home_team_season_id,away_team_season_id').eq('tournament_id', tour.id)
  const { data: seasons } = await supabase.from('team_seasons').select('id,team_id')
  const { data: teams } = await supabase.from('teams').select('id,name').eq('source', 'ppl')
  const teamName = new Map((teams ?? []).map((t) => [t.id as string, t.name as string]))
  const seasonTeam = new Map((seasons ?? []).map((s) => [s.id as string, teamName.get(s.team_id as string) ?? '']))

  const { data: matches } = await supabase.from('matches')
    .select('id,tie_id,category,pair1_player1_id,pair1_player2_id,pair2_player1_id,pair2_player2_id')
    .eq('tournament_id', tour.id)

  // Resolution goes NAME -> UPSTREAM SLUG -> our player id, never by matching
  // the published name against players.name.
  //
  // Two measured reasons. Our own names are not always upstream's: the row
  // behind `claudia-jensen` is stored as "LLi 10 Claudia Jensen", corrupted
  // by a bad ranking-feed name. And upstream keeps nicknames in its registry
  // ("Leonel \"Tolito\" Aguirre"), so any cleanup we apply moves our copy
  // further from theirs. The slug is the one identifier both sides agree on,
  // and Phase 2a already registered all 132 of them.
  const buildId = await fetchBuildId(nodeFetch)
  const payloadRes = await nodeFetch(`${PPL_ORIGIN}/_next/data/${buildId}/tournament/${SLUG}.json`)
  if (payloadRes.status !== 200) throw new Error(`payload fetch: HTTP ${payloadRes.status}`)
  const payload = JSON.parse(await payloadRes.text())
  const rows = payload?.pageProps?.broadcastContext?.playerRowsById ?? {}

  const slugByName = new Map<string, string[]>()
  for (const [slug, row] of Object.entries(rows as Record<string, any>)) {
    const v = row?.values ?? row
    for (const n of [v?.displayName, [v?.firstName, v?.lastName].filter(Boolean).join(' ')]) {
      if (!n) continue
      const k = nameKey(String(n))
      if (!slugByName.has(k)) slugByName.set(k, [])
      if (!slugByName.get(k)!.includes(slug)) slugByName.get(k)!.push(slug)
    }
  }
  console.log(`upstream registry: ${Object.keys(rows).length} players, ${slugByName.size} name keys`)

  const { data: reg } = await supabase.from('entity_external_ids')
    .select('entity_id,external_id').eq('entity_type', 'player').eq('source', 'ppl')
  const idBySlug = new Map((reg ?? []).map((r) => [r.external_id as string, r.entity_id as string]))

  const resolve = (name: string): { id: string | null; why: string } => {
    const slugs = slugByName.get(nameKey(name)) ?? []
    if (slugs.length === 0) return { id: null, why: 'no upstream slug' }
    if (slugs.length > 1) return { id: null, why: `ambiguous slug (${slugs.length})` }
    const id = idBySlug.get(slugs[0])
    if (!id) return { id: null, why: `slug ${slugs[0]} not registered` }
    return { id, why: slugs[0] }
  }

  const writes: Array<{ matchId: string; payload: Record<string, string>; desc: string }> = []
  const unresolved = new Set<string>()
  let skippedFilled = 0, noTie = 0

  for (const court of parsed) {
    const tie = (ties ?? []).find((t) => {
      const h = seasonTeam.get(t.home_team_season_id as string) ?? ''
      const a = seasonTeam.get(t.away_team_season_id as string) ?? ''
      return alignLineupToTie(court, h, a) !== null
    })
    if (!tie) { noTie++; console.log(`  NO TIE for ${court.home.team} vs ${court.away.team} (${court.category})`); continue }

    const aligned = alignLineupToTie(
      court,
      seasonTeam.get(tie.home_team_season_id as string) ?? '',
      seasonTeam.get(tie.away_team_season_id as string) ?? '',
    )!

    const match = (matches ?? []).find((m) => m.tie_id === tie.id && m.category === court.category)
    if (!match) { noTie++; console.log(`  NO MATCH row for ${court.home.team} vs ${court.away.team} (${court.category})`); continue }

    const already = [match.pair1_player1_id, match.pair1_player2_id, match.pair2_player1_id, match.pair2_player2_id]
      .filter(Boolean).length === 4
    if (already && !FORCE) { skippedFilled++; continue }

    const slots = [
      ['pair1_player1_id', aligned.homePlayers[0]],
      ['pair1_player2_id', aligned.homePlayers[1]],
      ['pair2_player1_id', aligned.awayPlayers[0]],
      ['pair2_player2_id', aligned.awayPlayers[1]],
    ] as const

    const payload: Record<string, string> = {}
    let ok = true
    for (const [col, nm] of slots) {
      const r = resolve(nm)
      if (!r.id) { unresolved.add(`${nm} (${r.why})`); ok = false; continue }
      payload[col] = r.id
    }
    // All four or none: a half-filled card is worse than TBD, because it
    // implies the missing player simply has no profile.
    if (!ok) continue

    writes.push({
      matchId: match.id as string,
      payload,
      desc: `${court.category.padEnd(5)} ${aligned.flipped ? '[flipped] ' : ''}${seasonTeam.get(tie.home_team_season_id as string)} ${aligned.homePlayers.join(' / ')}  vs  ${seasonTeam.get(tie.away_team_season_id as string)} ${aligned.awayPlayers.join(' / ')}`,
    })
  }

  console.log(`\n=== WOULD WRITE (${writes.length}) ===`)
  for (const w of writes) console.log(`  ${w.desc}`)
  console.log(`\n  already filled, skipped : ${skippedFilled}`)
  console.log(`  no tie / match matched  : ${noTie}`)
  console.log(`  unresolved players      : ${unresolved.size}`)
  for (const u of unresolved) console.log(`     ${u}`)

  if (!APPLY) { console.log(`\nDry run complete. Nothing written.`); return }
  if (writes.length === 0) { console.log('\nNothing to write.'); return }

  let n = 0
  for (const w of writes) {
    const { error } = await supabase.from('matches').update(w.payload).eq('id', w.matchId)
    if (error) throw new Error(`update failed (${w.matchId}): ${error.message}`)
    n++
  }
  console.log(`\nApply complete. ${n} match(es) updated.`)
}

main().catch((e) => { console.error(e); process.exit(1) })
