-- Tournament bagel LINE market — replaces per-match `match.bagel`
-- (disabled by 20260930090000_stop_new_match_bagels.sql).
--
-- One market per Premier event × category, generated by padelgod's
-- market-generator before the main draw starts:
--   "Will the women's main draw at Rotterdam have 3 or more 6-0 sets?"
-- Settled by resolver `tournament.bagel_count_at_least_v1`
-- (padelgod/src/lib/market-resolvers/bagel-count.ts).
--
-- WHY A LINE: measured on 2025-01 → 2026-09 completed main draws, 100% of Major
-- draws and ~80% of P1 draws had at least one 6-0. "Any bagel in this draw?" is
-- a foregone YES; a count threshold is not.
--
-- CALIBRATION (per level × category, main draw only, completed events):
-- the line is the threshold whose smoothed frequency (k+1)/(n+2) lands closest
-- to 50%; `seedProb` is that smoothed frequency. Raw per-event bagel counts:
--   major men   n=7   2,2,3,3,3,4,5          → 4+  (2/7)   seed 0.333
--   major women n=7   1,4,4,4,5,5,8          → 5+  (3/7)   seed 0.444
--   p1 men      n=17  0,0,0,0,1,2,2,3,3,3,3,4,4,4,4,4,5 → 4+ (7/17) seed 0.421
--   p1 women    n=16  0,1,1,1,2,2,3,3,3,5,5,5,5,6,6,6   → 4+ (6/16) seed 0.389
--   p2 men      n=15  0,0,0,0,0,0,1,1,1,2,2,2,3,3,4     → 2+ (6/15) seed 0.412
--   p2 women    n=15  0,0,0,1,1,2,2,2,2,2,3,4,4,5,7     → 3+ (5/15) seed 0.353
-- Levels with no entry (finals, fip_platinum, …) get NO market by design.
--
-- The question and rules each market is judged by are rendered in all five
-- app locales by the generator into `question_snapshot` / `rules_snapshot`.
-- `question_i18n` below is only a fallback and never shown for markets the
-- generator writes.

INSERT INTO market_templates
  (key, question_i18n, horizon, trigger, lock_rule, resolver_key,
   seed_source, max_loss_guacas, params, gates, enabled)
VALUES (
  'tournament.bagel_line',
  '{"en":"Will this main draw have {line} or more 6-0 sets?",
    "es":"¿Habrá {line} o más sets 6-0 en este cuadro principal?",
    "pt":"Haverá {line} ou mais sets 6-0 neste quadro principal?",
    "it":"Ci saranno {line} o più set finiti 6-0 in questo tabellone principale?",
    "fr":"Y aura-t-il {line} sets 6-0 ou plus dans ce tableau principal ?"}'::jsonb,
  'tournament', 'draw.released', 'round_first_ball',
  'tournament.bagel_count_at_least_v1',
  'fixed', 12000,
  '{"lines": {
     "major": {"men": {"line": 4, "seedProb": 0.333}, "women": {"line": 5, "seedProb": 0.444}},
     "p1":    {"men": {"line": 4, "seedProb": 0.421}, "women": {"line": 4, "seedProb": 0.389}},
     "p2":    {"men": {"line": 2, "seedProb": 0.412}, "women": {"line": 3, "seedProb": 0.353}}
   },
   "calibration": "2025-01..2026-09 completed Premier main draws; smoothed (k+1)/(n+2)"}'::jsonb,
  '{}'::jsonb,
  true
)
ON CONFLICT (key) DO NOTHING;
